### PR TITLE
Fix for spdlog link and tests

### PR DESCRIPTION
**Pull request by gdmiron**
Fix for linking to spdlog through chemicalfun 0.1.6. 
Fix for failing test at Psat on MacOS.

### CODE REVIEW

**Comment by gdmiron** [comment]
@allanleal Do you have any idea as to why the CI in actions does not find chemicalfun but the other CI does?

**Comment by allanleal** [comment]
I'm also experiencing a similar issue. Interesting. In my case, it complains about not finding optima 0.2.14 (but it exists, like your chemicalfun 0.1.6)

https://github.com/reaktoro/reaktoro/actions/runs/3549598407/jobs/5963176973

**Comment by allanleal** [comment]
@gdmiron After many hours, I think I found the issue. In the GitHub action, only packages with extension `.tar.bz2` are being considered (due to cache mechanism requirements). However, new packages have now been created with the new `.conda` extension ([see here](https://docs.conda.io/projects/conda/en/latest/user-guide/concepts/packages.html#conda-file-format). 

You notice here that the latest chemicalfun package has this extension, so it is not found during the `conda devenv` execution.
https://anaconda.org/conda-forge/chemicalfun/files?page=1

I'll fix this.

**Review by allanleal — APPROVED** [review]
Good to go - no more changes needed from my side.

**Comment by gdmiron** [comment]
@allanleal thanks a lot!

**Pull request merged**
